# Development
version: '3.7'
services:
  manual:
    image: ${OUT_IMG}
    build:
      context: ${DKR_CMP_CONTEXT}
      dockerfile: docker/dev/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
        ODC_DB_HOSTNAME: odc
        ODC_DB_DATABASE: ${ODC_DB_DATABASE}
        ODC_DB_USER: ${ODC_DB_USER}
        ODC_DB_PASSWORD: ${ODC_DB_PASSWORD}
        ODC_DB_PORT: 5432
    command: "tail -f /dev/null"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /Datacube/data:/Datacube/data
      - ${DKR_CMP_CONTEXT}/datasets:/manual_indexer
      - ${DKR_CMP_CONTEXT}/utils:/manual_indexer/utils
  odc:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${ODC_DB_DATABASE}
      - POSTGRES_USER=${ODC_DB_USER}
      - POSTGRES_PASSWORD=${ODC_DB_PASSWORD}
      