version: '3.4'
networks: 
  default:
    external:
      name: odc
services:
  manual:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
        - DB_HOSTNAME=odc-db
        - DB_DATABASE=datacube
        - DB_USER=dc_user
        - DB_PASSWORD=localuser1234
        - DB_PORT=5432