# Production
version: '3.7'
services:
  manual:
    build:
      context: ${DKR_CMP_CONTEXT}
      dockerfile: docker/prod/Dockerfile
    command: "tail -f /dev/null"
    environment:
        - DB_HOSTNAME=${DB_HOSTNAME}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_PORT=${DB_PORT}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /Datacube/data:/Datacube/data
    networks:
      odc: {}
networks: 
  odc:
    external: true
    name: odc